const CODES = {
  README_CONTRACT_MISSING: "README_CONTRACT_MISSING",
  README_CONTRACT_INVALID_JSON: "README_CONTRACT_INVALID_JSON",
  README_TREE_MISSING: "README_TREE_MISSING",
  CODE_INVENTORY_MISSING: "CODE_INVENTORY_MISSING",
  CODE_INVENTORY_INVALID_JSON: "CODE_INVENTORY_INVALID_JSON",
  CONTRACT_MISMATCH: "CONTRACT_MISMATCH",
  MISSING_PATH: "MISSING_PATH",
  OUTPUT_MISSING: "OUTPUT_MISSING",
  OUTPUT_MISMATCH: "OUTPUT_MISMATCH"
};

function createError(code, detail) {
  return { code, detail };
}

module.exports = { CODES, createError };
